### ISSUE TITLE
Hardcoded strings

### ISSUE THREAD

**Issue by yoavain** [yoavain/mediaportal-latest-media-handler#1]
http://forum.team-mediaportal.com/threads/latestmediahandler-v2-0-0-22.129072/page-8#post-1134515

From forum:
For a next new version, is it possible to change the hardcoded english label into language labels ?

Indeed, most of the labels are using the standard languages XML files except for the filter menu items in LatestMusicHandler.cs ("Display Most Played Music", "Display Latest Played Music" and "Display Latest Added Music") which are hardcoded.

**Comment by andrewjswan** [comment]
Fixed :) in 2.3.0.33
